14923 lisää koriin näkymään mahdollisuus hakea koria lisämuutokset
City-of-Turku/MIP_museumsinformationportal_ui pull request #48
Opened 2022-04-29 10:20 UTC by lthap

**QR koodin skannaamisesta suoraan muokkausnäkymään  - olennaisimmat muutokset (koriController.js):**
koriControlleriin lisätty funktio haeKoriNimellä, joka määrää muokkaukseen siirtymisen. 
Tässä otettu myös huomioon korin tyypin oikeellisuuden tarkistus. Koodi tulostaa virheen, jos Löytöjen lisäyksessä skannataan näyte-kori tai näytteiden lisäyksessä löytö-kori.

**%-kuvajaisen lisäys:**
muutettu korit.html ja valitse_kori.html placeholderi

2022-04-29 10:32 UTC, mipjk commented on app/korit/koriController.js
> +										vm.lisaaKoriin(data['features'][0]);
Entä jos tässä kohtaa vasta katsottaisiinkin korityyppi. Silloin ei tarvitse kahteen kertaan tehdä samaa asiaa, vaan toimii molemmille tyypeille + vielä rakennuksillekin, jos ne tulee joskus.

2022-04-29 10:35 UTC, mipjk requested changes
Korityyppi iffi vähän eri paikkaan niin ei tarvitse kahteen kertaan samaa koodia.

2022-04-29 10:35 UTC, mipjk commented on app/korit/koriController.js
> +										vm.lisaaKoriin(data['features'][0]);
Ja jollei ole sama korityyppi niin sitten heitetään virhe. Ehkä hiukan hifistelyä toi virheilmoitus.

2022-04-29 11:16 UTC, lthap commented
Oisko nyt parempi?

2022-05-02 06:33 UTC, lthap commented on app/korit/koriController.js
> +										vm.lisaaKoriin(data['features'][0]);
Nyt pitäisi olla kaikki ylimääräinen if-elseily pois

2022-05-02 06:34 UTC, lthap commented
> Korityyppi iffi vähän eri paikkaan niin ei tarvitse kahteen kertaan samaa koodia.

Tehty

2022-05-02 06:36 UTC, mipjk reviewed
Nyt on hyvä

2022-05-02 06:51 UTC, merged